-- Generated from crawled-products.json. Run after schema and seed-categories-subcategories.sql.
-- Products from crawl; image_url may be external (run download-product-images.js and replace with /product-images/... if needed).

INSERT INTO public.products (name_en, name_he, description_en, description_he, price, image_url, category_id, subcategory_id, stock_status, specs) VALUES
('ZYLO Nicotine Pouches Berry Ice 6mg', 'ZYLO Nicotine Pouches Berry Ice 6mg', 'Zylo non-tobacco nicotine pouches 20 pouches/pack Color white Dive into a burst of freshness with Berry Ice This ﬂavor combines the juicy sweetness of ripe berries with a refreshing touch of ice Each pouch delivers a balanced blend that awakens your senses and leaves a cool pleasant sensation in', NULL, 25, 'https://www.cig.co.il/images/detailed/18/zylo-nicotine-pouches-berry-ice-6mg.webp', 'tobacco-substitutes', 'zylo-nicotine-pouches', 'in_stock', NULL),
('ZYLO Nicotine Pouches Peppermint 9mg', 'ZYLO Nicotine Pouches Peppermint 9mg', 'Zylo non-tobacco nicotine pouches 20 pouches/pack Color white Intense peppermint as cool as an Arctic breeze A tingly awakening sensation Like inhaling frosty air atop a glacier Perfect for a refreshing break during warm days', NULL, 25, 'https://www.cig.co.il/images/detailed/18/zylo-nicotine-pouches-peppermint-9mg.webp', 'tobacco-substitutes', 'zylo-nicotine-pouches', 'in_stock', NULL),
('ZYLO Nicotine Pouches Peppermint 6mg', 'ZYLO Nicotine Pouches Peppermint 6mg', 'Zylo non-tobacco nicotine pouches 20 pouches/pack Color white Intense peppermint as cool as an Arctic breeze A tingly awakening sensation Like inhaling frosty air atop a glacier Perfect for a refreshing break during warm days', NULL, 25, 'https://www.cig.co.il/images/detailed/18/zylo-nicotine-pouches-peppermint-6mg.webp', 'tobacco-substitutes', 'zylo-nicotine-pouches', 'in_stock', NULL),
('ZYLO Nicotine Pouches Spearmint 9mg', 'ZYLO Nicotine Pouches Spearmint 9mg', 'Zylo non-tobacco nicotine pouches 20 pouches/pack Color white Enjoy crisp menthol freshness balanced with fresh and sweet tasting spearmint ﬂavours with Zylo Spearmint pouches The delicate ﬂavours allow for a more subtle mint experience', NULL, 25, 'https://www.cig.co.il/images/detailed/18/zylo-nicotine-pouches-spearmint-9mg.webp', 'tobacco-substitutes', 'zylo-nicotine-pouches', 'in_stock', NULL),
('ZYLO Nicotine Pouches Spearmint 6mg', 'ZYLO Nicotine Pouches Spearmint 6mg', 'Zylo non-tobacco nicotine pouches 20 pouches/pack Color white Enjoy crisp menthol freshness balanced with fresh and sweet tasting spearmint ﬂavours with Zylo Spearmint pouches The delicate ﬂavours allow for a more subtle mint experience', NULL, 25, 'https://www.cig.co.il/images/detailed/18/zylo-nicotine-pouches-spearmint-6mg.webp', 'tobacco-substitutes', 'zylo-nicotine-pouches', 'in_stock', NULL),
('ZYLO Nicotine Pouches Mint Ice 9mg', 'ZYLO Nicotine Pouches Mint Ice 9mg', 'Zylo non-tobacco nicotine pouches 20 pouches/pack Color white Mint Ice is the ideal choice for those who love an intense cooling sensation This pouch provides a hit of refreshing menthol that envelops you in a wave of coolness', NULL, 25, 'https://www.cig.co.il/images/detailed/18/zylo-nicotine-pouches-mint-ice-9mg.webp', 'tobacco-substitutes', 'zylo-nicotine-pouches', 'in_stock', NULL),
('ZYLO Nicotine Pouches Mint Ice 6mg', 'ZYLO Nicotine Pouches Mint Ice 6mg', 'Zylo non-tobacco nicotine pouches 20 pouches/pack Color white Mint Ice is the ideal choice for those who love an intense cooling sensation This pouch provides a hit of refreshing menthol that envelops you in a wave of coolness', NULL, 25, 'https://www.cig.co.il/images/detailed/18/zylo-nicotine-pouches-mint-ice-6mg.webp', 'tobacco-substitutes', 'zylo-nicotine-pouches', 'in_stock', NULL),
('Neafs TEO HNB Device (Iqos Heets Compatible)', 'Neafs TEO HNB Device (Iqos Heets Compatible)', 'Neafs Teo is advanced well crafted Heating device for Neafs sticks and all other Iqos compatible heat sticks What’s In the BOX? TEO deviceUSB charging cableInstruction manual Specifications Pre heating time 20 secondsCharging time 120 minsBattery capacity 1700mAhBattery life 20 sticks NEAFS', NULL, 250, 'https://www.cig.co.il/images/detailed/18/neafs-teo-hnb-device-iqos-heets-compatible.webp', 'tobacco-substitutes', 'tobacco-heating-devices', 'in_stock', NULL),
('HiTaste P5 HNB Device (IQOS Heets Compatible)', 'HiTaste P5 HNB Device (IQOS Heets Compatible)', 'HiTaste P5 HNB is Heat-not-burn products Heat-not-burn products heated tobacco or HNB are electronic devices which heat processed tobacco without burning it combustion which is suitable for IQOS HEETS Fiit sticks in Korea Marlboro HeatSticks and most herbal HeatSticks on the market HiTaste P5', NULL, 175, 'https://www.cig.co.il/images/detailed/17/hitaste-p5-hnb-device-iqos-heets-compatible.jpg', 'tobacco-substitutes', 'tobacco-heating-devices', 'in_stock', NULL),
('NEAFS Original (Tobacco) 1.5% Nicotine Sticks - 200 Sticks', 'NEAFS Original (Tobacco) 1.5% Nicotine Sticks - 200 Sticks', 'Realistic classic Virginia tobacco taste without the smell and without tobacco Perfect for any occasion NEAFS Original will surely leave you satisfied Featuring a rich flavour with earthly undertones and a smooth finish for the best experience at your fingertips Enjoy a guilt-free time NEAFS', NULL, 180, 'https://www.cig.co.il/images/detailed/15/neafs-original-tobacco-1-5-nicotine-sticks---200-sticks.jpg', 'tobacco-substitutes', 'neafs-heating-sticks', 'in_stock', NULL),
('NEAFS Blueberry 1.5% Nicotine Sticks - 200 Sticks', 'NEAFS Blueberry 1.5% Nicotine Sticks - 200 Sticks', 'Sweet and slightly sour fresh blueberries taste with floral undertones Featuring a very aromatic taste and smell that any fruit-lover will enjoy Enjoy a comfortable and smooth experience of fresh fields anywhere A truly unforgettable adventure of taste reminiscent of daydreaming NEAFS', NULL, 180, 'https://www.cig.co.il/images/detailed/18/neafs-blueberry-1-5-nicotine-sticks---200-sticks.webp', 'tobacco-substitutes', 'neafs-heating-sticks', 'in_stock', NULL),
('NEAFS Original (Tobacco) 1.5% Nicotine Sticks - 20 Sticks (1 Pack)', 'NEAFS Original (Tobacco) 1.5% Nicotine Sticks - 20 Sticks (1 Pack)', 'Realistic classic Virginia tobacco taste without the smell and without tobacco Perfect for any occasion NEAFS Original will surely leave you satisfied Featuring a rich flavour with earthly undertones and a smooth finish for the best experience at your fingertips Enjoy a guilt-free time NEAFS', NULL, 20, 'https://www.cig.co.il/images/detailed/17/neafs-original-tobacco-1-5-nicotine-sticks---20-sticks-1-pack.webp', 'tobacco-substitutes', 'neafs-heating-sticks', 'in_stock', NULL),
('NEAFS Blueberry 1.5% Nicotine Sticks - 20 Sticks (1 Pack)', 'NEAFS Blueberry 1.5% Nicotine Sticks - 20 Sticks (1 Pack)', 'Sweet and slightly sour fresh blueberries taste with floral undertones Featuring a very aromatic taste and smell that any fruit-lover will enjoy Enjoy a comfortable and smooth experience of fresh fields anywhere A truly unforgettable adventure of taste reminiscent of daydreaming NEAFS', NULL, 20, 'https://www.cig.co.il/images/detailed/17/neafs-blueberry-1-5-nicotine-sticks---20-sticks-1-pack.webp', 'tobacco-substitutes', 'neafs-heating-sticks', 'in_stock', NULL),
('NEAFS Menthol 1.5% Nicotine Sticks - 200 Sticks', 'NEAFS Menthol 1.5% Nicotine Sticks - 200 Sticks', 'Classic crisp and refreshing menthol taste anywhere Featuring a bold and refreshing menthol taste with a clean aftertaste that is sure to refresh your day! Pure freshness pure menthol pure happiness NEAFS Menthol are tobacco free sticks that offer excellent taste packed with our premium tea', NULL, 180, 'https://www.cig.co.il/images/detailed/15/neafs-menthol-1-5-nicotine-sticks---200-sticks.jpg', 'tobacco-substitutes', 'neafs-heating-sticks', 'in_stock', NULL),
('NEAFS Coffee 1.5% Nicotine Sticks - 200 Sticks', 'NEAFS Coffee 1.5% Nicotine Sticks - 200 Sticks', 'Enjoy the experience of a cup of coffee on the go! Featuring a pure dark roast coffee aroma leaving you reminiscent of a rich flavour latte enjoyed on a nice sunny day A perfect “pick-you-up” at your fingertips! An unforgettably smooth experience NEAFS Coffee are tobacco free sticks that offer', NULL, 180, 'https://www.cig.co.il/images/detailed/15/neafs-coffee-1-5-nicotine-sticks---200-sticks.jpg', 'tobacco-substitutes', 'neafs-heating-sticks', 'in_stock', NULL),
('NEAFS Menthol 1.5% Nicotine Sticks - 20 Sticks (1 Pack)', 'NEAFS Menthol 1.5% Nicotine Sticks - 20 Sticks (1 Pack)', 'Classic crisp and refreshing menthol taste anywhere Featuring a bold and refreshing menthol taste with a clean aftertaste that is sure to refresh your day! Pure freshness pure menthol pure happiness NEAFS Menthol are tobacco free sticks that offer excellent taste packed with our premium tea', NULL, 20, 'https://www.cig.co.il/images/detailed/17/neafs-menthol-1-5-nicotine-sticks---20-sticks-1-pack.webp', 'tobacco-substitutes', 'neafs-heating-sticks', 'in_stock', NULL),
('NEAFS Coffee 1.5% Nicotine Sticks - 20 Sticks (1 Pack)', 'NEAFS Coffee 1.5% Nicotine Sticks - 20 Sticks (1 Pack)', 'Enjoy the experience of a cup of coffee on the go! Featuring a pure dark roast coffee aroma leaving you reminiscent of a rich flavour latte enjoyed on a nice sunny day A perfect “pick-you-up” at your fingertips! An unforgettably smooth experience NEAFS Coffee are tobacco free sticks that offer', NULL, 20, 'https://www.cig.co.il/images/detailed/17/neafs-coffee-1-5-nicotine-sticks---20-sticks-1-pack.webp', 'tobacco-substitutes', 'neafs-heating-sticks', 'in_stock', NULL);