-- Generated from crawled-products.json. Run after schema and seed-categories-subcategories.sql.
-- Products from crawl; image_url may be external (run download-product-images.js and replace with /product-images/... if needed).

INSERT INTO public.products (name_en, name_he, description_en, description_he, price, image_url, category_id, subcategory_id, stock_status, specs) VALUES
('AVCT VooPoo Drag X / Drag S 510 Adapter', 'AVCT VooPoo Drag X / Drag S 510 Adapter', 'The Voopoo Drag S/ Drag 510 Adapter is designed so you could have your own 510 thread atomizer tank on the lovely Drag X / Drag S mod Parameters Type 510 AdapterFit for Voopoo Drag S/ Drag X Mod Feature Connected the 510 thread atomizer Quantity 1pcs', NULL, 25, 'https://www.cig.co.il/images/detailed/12/avct-voopoo-drag-x-drag-s-510-adapter.jpg', 'accessories', 'thread-adapters', 'in_stock', NULL),
('Stainless steel resin ring 510 Drip Tip', 'Stainless steel resin ring 510 Drip Tip', 'High quality 510 stainless steel + resin drip tip', NULL, 25, 'https://www.cig.co.il/images/detailed/18/stainless-steel-resin-ring-510-drip-tip.webp', 'accessories', 'replacement-drip-tips', 'in_stock', NULL),
('Innokin Zlide Top II 510 RDL Drip Tip - Black', 'Innokin Zlide Top II 510 RDL Drip Tip - Black', 'Made of teflonFor any atomizer that can accept type 510 mouthpieceIdeal for RDL type of vaping', NULL, 8, 'https://www.cig.co.il/images/detailed/17/innokin-zlide-top-ii-510-rdl-drip-tip---black.webp', 'accessories', 'replacement-drip-tips', 'in_stock', NULL),
('Stainless steel resin cross 510 drip tip', 'Stainless steel resin cross 510 drip tip', 'High quality 510 stainless steel + resin drip tip', NULL, 25, 'https://www.cig.co.il/images/detailed/12/stainless-steel-resin-cross-510-drip-tip.jpg', 'accessories', 'replacement-drip-tips', 'in_stock', NULL),
('Cotton Bacon Prime by Wick N Vape', 'Cotton Bacon Prime by Wick N Vape', 'Wick N Vape brings us a Cotton Bacon Prime - new and improved version of a classic favorite specifically formulated for vaping Cotton Bacon Prime is perfect for squonking tanks and rebuildable atomizers Cotton Bacon Prime features 33% faster absorption and much easier separation This bacon doesn', NULL, 36, 'https://www.cig.co.il/images/detailed/17/cotton-bacon-prime-by-wick-n-vape.webp', 'accessories', 'cotton', 'in_stock', NULL),
('AVCT Shoelace vape cotton - 24pcs', 'AVCT Shoelace vape cotton - 24pcs', 'AVCTVAPE shoelace vape cotton is specially designed for keen vaper s only use 100% natural purified Cotton material AVCTVape Vape cotton pack included 20 PCS Shoelace Vape Cotton and 4 PCS Ordinary Cotton The 100% Organic Cotton is great for RDA / RTA / RDTA Vape Atomizer Shoelace cotton is designed', NULL, 20, 'https://www.cig.co.il/images/detailed/12/avct-shoelace-vape-cotton---24pcs.jpg', 'accessories', 'cotton', 'in_stock', NULL),
('COTN Threads - Prebuilt cotton', 'COTN Threads - Prebuilt cotton', 'COTN Threads delivers a convenient set of wicking elements to the rebuildable accessory segment presenting a resealable bag of 20 organic cotton wicks in a pre-rolled configuration with plastic tube end for a ready-to-use set-up The steps to using the COTN Threads are incredibly easy that', NULL, 20, 'https://www.cig.co.il/images/detailed/19/cotn_threads_-_prebuilt_cotton_2.webp', 'accessories', 'cotton', 'in_stock', NULL),
('Lost Vape Centaurus Tank Replacement Bubble Glass 5ml', 'Lost Vape Centaurus Tank Replacement Bubble Glass 5ml', 'Features & Specifications 5mlBubble GlassFit for Lost Vape Centaurus / Centaurus Quest Tank Compatibilty LOST VAPE Centaurus Sub Ohm Tank What s in the Box? ﻿1 x Replacement Tank Glass', NULL, 15, 'https://www.cig.co.il/images/detailed/17/lost-vape-centaurus-tank-replacement-bubble-glass-5ml.webp', 'accessories', 'replacement-glass', 'in_stock', NULL),
('Justfog Q16 Pro Glass 1.9ml Replacement', 'Justfog Q16 Pro Glass 1.9ml Replacement', 'This is a replacement Pyrex glass for the Q16 PRO clearomizer Note this is really only for the Q16 PRO clearomizer with top fill and not for the normal Q16 bottom fill you get 1x pcs of Justfog replacment Glass', NULL, 17, 'https://www.cig.co.il/images/detailed/19/3077_12082020170400_large.webp', 'accessories', 'replacement-glass', 'in_stock', NULL),
('Vandyvape BSKR V2 MTL PEI Tube', 'Vandyvape BSKR V2 MTL PEI Tube', 'The Vandyvape BSKR V2 MTL PEI Tube is designed for Vandyvape BSKR V2 MTL RTA 1 x BSKR V2 MTL / PEI Tube Capacity 3ml', NULL, 10, 'https://www.cig.co.il/images/detailed/19/Vandyvape-BSKR-V2-MTL-pei-Tube.webp', 'accessories', 'replacement-glass', 'in_stock', NULL),
('FreeMax M Pro 2/3 Replacement Glass 5ml (1-pack)', 'FreeMax M Pro 2/3 Replacement Glass 5ml (1-pack)', 'FreeMax M Pro 2 Replacement Glass Tube 5mlPhysical Parameter Capacity 5ml bubble 2ml PCTG Packing list 1 x M Pro 2 Replacement Glass Tube', NULL, 20, 'https://www.cig.co.il/images/detailed/15/freemax-m-pro-2-3-replacement-glass-5ml-1-pack.jpg', 'accessories', 'replacement-glass', 'in_stock', NULL),
('Innokin Zenith II 5ml Replacement Glass Tube', 'Innokin Zenith II 5ml Replacement Glass Tube', '1pcs - Replacement tank 5 5ml for Innokin Zenith II', NULL, 15, 'https://www.cig.co.il/images/detailed/15/innokin-zenith-ii-5ml-replacement-glass-tube.jpg', 'accessories', 'replacement-glass', 'in_stock', NULL),
('SMOK TFV8 Baby Replacement Glass Tube', 'SMOK TFV8 Baby Replacement Glass Tube', '1 pcs* SMOK TFV8 Baby Replacement Glass Tube Diameter 21 5mm Height 19mm', NULL, 10, 'https://www.cig.co.il/images/detailed/18/smok-tfv8-baby-replacement-glass-tube.webp', 'accessories', 'replacement-glass', 'in_stock', NULL),
('Vaporesso Sky Solo Replacement Glass 3.5ml', 'Vaporesso Sky Solo Replacement Glass 3.5ml', 'The Vaporesso Sky Solo Replacement Bubble Glass Tube features a unique bubbled design with a large 3 5mL capacity for long vape session and a shorter profile Don’t replace your entire Vaporesso Sky Solo Kit get this replacement glass instead! Compatible with Vaporesso SKY SOLO Kit It comes with 1x –', NULL, 20, 'https://www.cig.co.il/images/detailed/18/vaporesso-sky-solo-replacement-glass-3-5ml.webp', 'accessories', 'replacement-glass', 'in_stock', NULL),
('Vaporesso Cascade Mini Replacement Glass Tube 3.5ml', 'Vaporesso Cascade Mini Replacement Glass Tube 3.5ml', 'The high quality Vaporesso Cascade Mini Replacement Glass Tube is perfectly designed for the Vaporesso Cascade Mini Subohm Tank with 3 5ml e-juice capacity Made of advanced pyrex glass the Cascade Mini Glass Tube is very solid and easy to clean Just get it as a spare part for your Vaporesso Cascade', NULL, 15, 'https://www.cig.co.il/images/detailed/9/vaporesso-cascade-mini-replacement-glass-tube-3-5ml.jpg', 'accessories', 'replacement-glass', 'in_stock', NULL),
('Protective Silicone Seal for Centaurus / Uforce-L / Maat Bubble Glass', 'Protective Silicone Seal for Centaurus / Uforce-L / Maat Bubble Glass', 'Material Silicon Item Protective Seal Ring Quantity 1 pcs Fits Centaurus / Uforce-L / Maat bubble glass', NULL, 15, 'https://www.cig.co.il/images/detailed/18/bubble-glass-protective-silicon-seal-ring-for-centaurus-uforce-l-maat-tanks.webp', 'accessories', 'replacement-glass', 'in_stock', NULL),
('O x v a 3 In One Charging Cable', 'O x v a 3 In One Charging Cable', 'Oxva 3 In One Charging Cable Compatible with MICRO USB USB-C and LIGHTNING cable Regardless of whether you use an Android Apple or any other device with a USB-C micro-USB or Lightning port the OXVA 3-in-1 USB cable has you covered It can even handle all devices at the same time as this cable allows you to', NULL, 20, 'https://www.cig.co.il/images/detailed/20/oxva-usb.cable.webp', 'accessories', 'chargers', 'in_stock', NULL),
('LiitoKala LII-C2 Battery Charger', 'LiitoKala LII-C2 Battery Charger', 'Description LiitoKala Lii-C2 is a smart universal charger that is capable of charging almost all Li-ion Ni-MH NiCd batteries It can detect battery type and charge the battery automatically under your selected charging current The Lii-C2 features a USB-C input port and a general USB output port', NULL, 65, 'https://www.cig.co.il/images/detailed/18/liitokala-lii-c2-battery-charger.webp', 'accessories', 'chargers', 'in_stock', NULL),
('LiitoKala Lii-100B Battery Charger', 'LiitoKala Lii-100B Battery Charger', 'LIITOKALA charger LII-100B for NiMH / CD batteries Li-Ion IMR 1 slot Charger for rechargeable batteries type NiMH / CD Li-Ion IMR 1 position The charger automatically detects the type of battery and is compatible with a variety of batteries Specifications Input Micro USB DC 5V / 1A Output voltage 4', NULL, 35, 'https://www.cig.co.il/images/detailed/18/liitokala-lii-100b-battery-charger.webp', 'accessories', 'chargers', 'in_stock', NULL),
('LiitoKala LII-M4S Battery Charger', 'LiitoKala LII-M4S Battery Charger', 'Functional characteristics 1 New touch control function 2 Using Type-C interface for DC5 0v input 3 Four optional charging currents 300mA * 4/500mA * 4/700mA * 2/1000mA * 2 4 Two stage discharge current 250mA * 4/500mA * 4 5 It is possible to charge batteries of different specifications', NULL, 160, 'https://www.cig.co.il/images/detailed/18/liitokala-lii-m4s-battery-charger.webp', 'accessories', 'chargers', 'in_stock', NULL),
('XTAR PB2S 18650 &amp; 21700 Fast Charger &amp; Power Bank', 'XTAR PB2S 18650 &amp; 21700 Fast Charger &amp; Power Bank', 'The XTAR PB2S is a versatile portable battery charger that combines compact design with powerful functionality It is designed to charge lithium-ion batteries and can also function as a power bank for your electronic devices Key Features Supports charging of various lithium-ion battery types', NULL, 130, 'https://www.cig.co.il/images/detailed/18/xtar-pb2s-18650-21700-fast-charger-power-bank-2.webp', 'accessories', 'chargers', 'in_stock', NULL),
('Vapcell Q2S-C 2-Slot 2X1AMP Smart Battery Charger', 'Vapcell Q2S-C 2-Slot 2X1AMP Smart Battery Charger', 'Vapcell Q2S-C Charger Parameters ModelQ2S-C InputDC 5V 2A Constant Current1A*2 Cut-off Voltage4 2V±0 1 Apply to Li-ion/IMR 3 7V10340 RCR123 /10440/14500/16340/16650/17500/17650/17670/18350/18490/18500/18650/22650/26500/26650/20650/22500/20700/21700 Package ContentCharger', NULL, 40, 'https://www.cig.co.il/images/detailed/18/vapcell-q2s-c-2-slot-2x1amp-smart-battery-charger.webp', 'accessories', 'chargers', 'in_stock', NULL),
('Sony VTC6 18650 3000mAh 20A/30A Battery', 'Sony VTC6 18650 3000mAh 20A/30A Battery', 'Brand Sony Energy | Murata Model US18650VTC6 VTC6 Size 18650 Nominal Capacity 3000mAh Nominal Voltage 3 6V Maximum Voltage 4 2V Discharge 20A Maximum Continuous 30A Maximum Continuous with 80 deg C cutoff Style Flat Top Protected NO UNPROTECTED Approximate Dimensions 18 5mm x 65 2mm Approximate', NULL, 50, 'https://www.cig.co.il/images/detailed/10/sony-vtc6-18650-3000mah-20a-30a-battery.jpg', 'accessories', 'batteries', 'in_stock', NULL),
('Samsung 40T 21700 4000mAh 35A Battery', 'Samsung 40T 21700 4000mAh 35A Battery', 'As one of the top-performing 21700 batteries from Samsung the 40T INR21700-40T offers 4 000mAh in capacity with a 35A maximum continuous discharge Brand Samsung Model INR21700-40T 40T Size 21700 Nominal Capacity 4000mAh Nominal Voltage 3 6V Maximum Voltage 4 2V Discharge Current 35A Maximum', NULL, 50, 'https://www.cig.co.il/images/detailed/12/samsung-40t-21700-4000mah-35a-battery.jpg', 'accessories', 'batteries', 'in_stock', NULL);